name: Build python app

on:
  push:
    branches: main

jobs:
  build-fastapi-app:
    name: Build FastAPI App
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      actions: read
      checks: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r fast-api-skeleton/content/requirements.txt
          pip install pytest

      - name: Unit Tests
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: true
          report-title: 'Unit Tests Report'

      - name: Git Leaks - Scanning for passwords, tokens, etc.
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

      - name: Sonar Scan
        run: echo "Run SonarQube scan"

